export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const USER_LOADED = "USER_LOADED";
export const USERS_LOADED = "USERS_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOG_OUT = "LOG_OUT";

export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";

export const MAP_LOADED = "MAP_LOADED";
export const MAP_ERROR = "MAP_ERROR";

export const PLACE_DATA_LOADED = "PLACE_DATA_LOADED";
export const PLACE_DATA_ERROR = "PLACE_DATA_ERROR";

export const PLACES_LOADED = "PLACES_LOADED";
export const PLACES_CLEAR = "PLACES_CLEAR";
export const PLACES_ERROR = "PLACES_ERROR";
